version: "3"
services:
  cat-service:
    build: ./services/cat-service/.
    ports:
      - "3001:3001"
    # environment:
    #   - OPEN_TELEMETRY_URL='http://192.168.1.6:4318/v1/traces'

  foo:
    build: ./services/foo/.
    ports:
      - "8000:8000"
    environment:
      - BAR_ENDPOINT=http://bar:5000/bar
      - AGENT_HOSTNAME=otel-collector

  bar:
    build: ./services/bar/.
    environment:
      - AGENT_HOSTNAME=otel-collector
  
  otel-collector:
    # platform: linux/amd64
    # image: otel/opentelemetry-collector:0.25.0
    # image: otel/opentelemetry-collector-contrib
    # container_name: otel-collector
    image: otel/opentelemetry-collector:0.61.0
    # command: [--config=/etc/otel-collector-config.yaml]
    ports:
      - "6831:6831"
      - "14268:14268"
      # - "4317:4317"
      # - "4318:4318"
      # - "4317:4317"
      # - "4318:4318"
    volumes:
      - ./config/otel-collector.yaml:/config/otel-collector.yaml
    command:
      - --config=/config/otel-collector.yaml

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    ports:
      - "3100:3100"
      - "55680:55680"
      # - "4317"
      # - "4318"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
      - ./example-data/tempo:/tmp/tempo
  
  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    # image: grafana/grafana:7.5.4
    image: grafana/grafana:9.4.3
    volumes:
      - ./config/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000"