receivers:
  otlp:
    protocols:
      grpc:
        # include_metadata: true
      http:
        # endpoint: "0.0.0.0:4318"
        cors:
          allowed_origins:
            - '*'
          allowed_headers:
            - '*'
        # include_metadata: true

processors:
  batch:

exporters:
  # otlp:
  #   endpoint: tempo:55680
  #   tls:
  #     insecure: true
  #   # insecure: true
  otlp:
    endpoint: tempo:4317
    # endpoint: tempo:55680
    tls:
      insecure: true
  logging:
    loglevel: debug
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp,logging]
    logs: 
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]